### PR TITLE
Wait for dom to load before refreshing Metamask opening page.

### LINKED ISSUE #2: Intermittent "Metamask failed to load" error
Often when the Metamask plugin is loaded for the first time, it shows an error that it wasn't loaded properly. This is fixed with a `page.reload()` which fixes the issue.

There is a small race condition where [this part of the code](https://github.com/TenKeyLabs/dappwright/blob/1e371819b775ab19d44f3943a21e017fef7f31ce/src/setup/setupMetamask.ts#L39) executes after the error page is displayed and the causes it to hang.

**To Reproduce**
Steps to reproduce:

Sometimes hard, but the condition happens much more often when executing tests with the playwright cli.

### PR DESCRIPTION
**Pull request by osis**
**Short description of work done**
Fixes #2 by waiting for the dom to load before reloading the page.

### PR Checklist

- [x] I have run linter locally
- [x] Update configuration the newest version (readme and const)
- [x] Rebased to master branch / merged master

### CODE REVIEW

File: src/setup/setupMetamask.ts [hunk 1]
```diff
@@ -34,7 +33,10 @@ export async function setupMetamask<Options = MetamaskOptions>(
 }
 
 const getWelcomScreen = async (browserContext: BrowserContext): Promise<Page> => {
```
Comment (RayzorFlash) [inline src/setup/setupMetamask.ts:35]: typo in `WelcomeScreen`, lol

**Review by RayzorFlash — APPROVED** [review]
